name: givtimer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.3
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_core: ^1.17.1
  flow_builder: ^0.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.1
  go_router: ^3.1.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.2
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.0.0-dev.2
  intl: ^0.17.0
  kplayer: ^0.2.4
  line_icons: ^2.0.1
  neon_circular_timer: ^0.0.7
  path_provider: ^2.0.10
  settings_ui: ^2.0.2
  uuid: ^3.0.6
  velocity_x: ^3.5.1
  very_good_analysis: ^3.0.0
  wave: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/ringtones/
    - assets/notification/
